travis:
  secure:
    BINSTAR_TOKEN: vjKxLWD/ZiV9uwgOiWnGdx1d5dpY/cq1di4x/x91Qb5mfyMDQOItLhssSfvY9ViKX272kgEmNxrjdqFJSE3+UHjIc8bqS3JsGBIfgvbBlGG+0G+vKIeBDzpbp8HUaAiLc7Fgu2yOJ7c0WlUOEdd+LO4jeFEdPZGEUkkjnrHqr/z0AwL9iOUHGGcwZ5TCgWfCb44IzUoFJi2qpNBDqnd1J72kmOalH70xrxu/a694UnBq7VSz2mntEwOmQyiE64P5RXgDubsYsd08VXd++l4jHcMNNsZwZYpCx6GVB3JFAtFxKCjIeDwe2V248cw2fSwtBICEEt9A41llbw/c08WDTnE5ifmR6/FSAbK2zZ6hiaNJP55mBawsqTVOievD9Fn8KGMDVgf1frC7nccz5F3/3y3o7KmkWrn3ngVIBkvWfSZ0UQY5QXNt6exX8RJ5tortfAk8bJIT1ZnoWGHes1BfAplUAsfHAXth5atWPhEV511nkKH7jExEqISgFe3sp2I+U5f1aeYSn8BTtC3QKywjpowV8JALA/80N2u8+sz4nk7FFQCl2CDElOGs1FXBh6Vj02rRnuKpx3AZtnisbDV9nYYvbUh+8A4Yis/kZnw9qxZYgk6d5EnGSlM7fFk7hccULyceSoVH8Pme/nYcQ+0U6Nyx58zpvRgx7IrpcMrGzUE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
