travis:
  secure:
    BINSTAR_TOKEN: CUvGD9cJn8fj3aZYn+VAe7vS9LdC9iKepI6ythgQIMuKONuntkX5NakNkUHYeZAZcjFl8iBcbNiqBlKBcd6m+lIcWw71ahZFXVcRCCy4M+/CJDL40Gcjl5YzxmI7Z9RIut11kin036XQsRGNcEwKk5muhKCE2dAs6Wlue0mjTxX5D9rKLKBIRSLuFbkjJxOyJjt/sioamU2ZYQsHDWP7ruxWw/SUSP/BN1fVPhX615snPtGYLRpxN19trG9cj4DBlM9cSJPnXAIFK4/C/mc4O96BGfHxHYgMAgz1Z2kgiAft6dO954wCkR8zYxV90A5/T7IOa2G6PWuP3I862G1Q97lP3pRpE5we5z3z10FY27dzKl9VMp319ZDAbQga4wq/7rlEJC5xxd7fOsjgMtHKWJ2vnhoMqB9ebLlL6yRXQOegw9DBzGGnEARTL64bSBRn5Elmg6i2iEDz4mMSoZa1uop1/T/z9KhGOlkxOOdQTBDbAkDYogFHlgZbSDe0DQskm8UAtxVL+XyXx2p6znA6snPANTYt6T1MHbEUNFOmP3TJJezWYjVNlD6BvqC0jFxJjOyKGsqFx1xdb4qrnqAocuDjSJxzTGW0C2RlUkfnf9ACP8o1/sEKlSEfofPOZfa8UYVBaYRaoD+O0CflE1o9/isP/7lVlDec//3wMgbUOzU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
